package ru.hostco.portal;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-08T12:11:01.844+03:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "portal", 
                  wsdlLocation = "file:src/main/resources/MedvedServiceClient.wsdl",
                  targetNamespace = "http://www.hostco.ru/portal") 
public class Portal_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.hostco.ru/portal", "portal");
    public final static QName PortalSOAP = new QName("http://www.hostco.ru/portal", "portalSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/MedvedServiceClient.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Portal_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/MedvedServiceClient.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Portal_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Portal_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Portal_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Portal_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Portal_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Portal_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Portal
     */
    @WebEndpoint(name = "portalSOAP")
    public Portal getPortalSOAP() {
        return super.getPort(PortalSOAP, Portal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Portal
     */
    @WebEndpoint(name = "portalSOAP")
    public Portal getPortalSOAP(WebServiceFeature... features) {
        return super.getPort(PortalSOAP, Portal.class, features);
    }

}
